# This workflow build docker image and push to GitHub repository.
#
name: Build and push docker

on:
  release:
    types: 
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker_push:
    name: Docker build and push to GH repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: vc-vantage/docker-push-github-repo-composite-action@v1
        with:
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docker-registry: ${{ env.REGISTRY }}
          docker-image: ${{ env.IMAGE_NAME }}
