# This workflow build docker image and push to GitHub repository.
#
name: Build and push docker
on:
  release:
    types: 
      - published

env:
  ECR_REGISTRY:               ${{ secrets.ECR_REGISTRY }}                   # AWS ECR registry (format: `aws_account_id.dkr.ecr.region.amazonaws.com`)
  ECR_AWS_ACCESS_KEY_ID:      ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}          # AWS Access Key
  ECR_AWS_SECRET_ACCESS_KEY:  ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}      # AWS Access Secret Key
  IMAGE_PREFIX:               ${{ secrets.IMAGE_PREFIX }}                   # optional: prefix for ECR image (must ending with "/")
  IMAGE_NAME:                 ${GITHUB_REPOSITORY/vc-vantage\/vantage-/}    # Image name

jobs:
  docker_push:
    name: Docker build and push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: vc-vantage/docker-push-ecr-composite-action@v1
        with:
          ecr-access-key:  ${{ env.ECR_AWS_ACCESS_KEY_ID }}
          ecr-secret-key:  ${{ env.ECR_AWS_SECRET_ACCESS_KEY }}
          docker-registry: ${{ env.ECR_REGISTRY }}
          docker-image:    ${{ env.IMAGE_PREFIX }}${{ env.IMAGE_NAME }}
