# This workflow build docker image and push to GitHub repository.
#
name: Build and push docker
on:
  release:
    types: 
      - published

env:
  REGISTRY:   secrets.ECR_REGISTRY                          # AWS ECR registry (format: `aws_account_id.dkr.ecr.region.amazonaws.com`)
  IMAGE_NAME: ${GITHUB_REPOSITORY/vc-vantage\/vantage-/}    # Image name

jobs:
  docker_push:
    name: Docker build and push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: vc-vantage/docker-push-ecr-composite-action@v1
        with:
          ecr-access-key: ${{ github.actor }}
          ecr-secret-key: ${{ secrets.GITHUB_TOKEN }}
          docker-registry: ${{ env.REGISTRY }}
          docker-image: ${{ env.IMAGE_NAME }}
