name: Semantic Release

on:
  push:
    branches:
      - $default-branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: vc-vantage/semantic-release-composite-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
