# This workflow publish new release based on Conventional Commits commit history.
#
# Use this workflow work best with "Semantic PR Check" workflow.
#
# For more information about Conventional Commits specitfaction, refer to https://www.conventionalcommits.org/
# For more information about Semantic Release, refer to https://semantic-release.gitbook.io/
#
name: Release

on:
  push:
    branches:
      - $default-branch

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vc-vantage/semantic-release-composite-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
